"""Constants and CSS selectors for the defuddle content extraction system."""

ENTRY_POINT_ELEMENTS = [
    "#post",
    ".post-content",
    ".post-body",
    ".article-content",
    "#article-content",
    ".article_post",
    ".article-wrapper",
    ".entry-content",
    ".content-article",
    ".instapaper_body",
    ".post",
    ".markdown-body",
    "article",
    '[role="article"]',
    "main",
    '[role="main"]',
    ".article-body",
    "#content",
    "body",
]

MOBILE_WIDTH = 600

BLOCK_ELEMENTS = [
    "div", "section", "article", "main", "aside", "header", "footer", "nav", "content",
]

PRESERVE_ELEMENTS = frozenset({
    "pre", "code", "table", "thead", "tbody", "tr", "td", "th",
    "ul", "ol", "li", "dl", "dt", "dd",
    "figure", "figcaption", "picture",
    "details", "summary",
    "blockquote",
    "form", "fieldset",
})

INLINE_ELEMENTS = frozenset({
    "a", "span", "strong", "em", "i", "b", "u", "code", "br", "small",
    "sub", "sup", "mark", "date", "del", "ins", "q", "abbr", "cite",
    "relative-time", "time", "font",
})

EXACT_SELECTORS = [
    "noscript",
    "template",
    'script:not([type^="math/"])',
    "style",
    "meta",
    "link",
    '.ad:not([class*="gradient"])',
    '[class^="ad-" i]',
    '[class$="-ad" i]',
    '[id^="ad-" i]',
    '[id$="-ad" i]',
    '[role="banner" i]',
    '[alt*="advert" i]',
    ".promo",
    ".Promo",
    "#barrier-page",
    ".alert",
    '[id="comments" i]',
    '[id="comment" i]',
    "header",
    '.header:not(.banner)',
    "#header",
    "#Header",
    "#banner",
    "#Banner",
    "nav",
    "ads-breadcrumbs",
    "ads-breadcrumb",
    ".navigation",
    "#navigation",
    ".hero",
    '[role="navigation" i]',
    '[role="dialog" i]',
    '[role*="complementary" i]',
    '[class*="pagination" i]',
    ".menu",
    "#menu",
    "#siteSub",
    ".previous",
    ".author",
    ".Author",
    '[class$="_bio"]',
    "#categories",
    ".contributor",
    ".date",
    "#date",
    "[data-date]",
    ".entry-meta",
    ".meta",
    ".tags",
    "#tags",
    ".toc",
    ".Toc",
    "#toc",
    ".headline",
    "#headline",
    "#title",
    "#Title",
    "#articleTag",
    # '[href*="/category"]',  # see issue #131
    # '[href*="/categories"]',  # see issue #131
    '[href*="/tag/"]',
    '[href*="/tags/"]',
    '[href*="/topics"]',
    '[href*="author"]',
    '[href*="#toc"]',
    '[href="#top"]',
    '[href="#Top"]',
    '[href="#page-header"]',
    '[href="#content"]',
    '[href="#site-content"]',
    '[href="#main-content"]',
    '[href^="#main"]',
    '[src*="author"]',
    "footer",
    ".aside",
    "aside",
    "button",
    "canvas",
    "date",
    "dialog",
    "fieldset",
    "form",
    'input:not([type="checkbox"])',
    "label",
    "option",
    "select",
    "textarea",
    "[hidden]",
    '[aria-hidden="true"]:not([class*="math"])',
    '[style*="display: none"]:not([class*="math"]):not(.footnoteContent)',
    '[style*="display:none"]:not([class*="math"]):not(.footnoteContent)',
    '[style*="visibility: hidden"]',
    '[style*="visibility:hidden"]',
    ".hidden",
    ".invisible",
    "instaread-player",
    'iframe:not([src*="youtube"]):not([src*="youtu.be"]):not([src*="vimeo"]):not([src*="twitter"]):not([src*="x.com"]):not([src*="datawrapper"])',
    '[class="logo" i]',
    "#logo",
    "#Logo",
    "#newsletter",
    "#Newsletter",
    ".subscribe",
    ".noprint",
    '[data-print-layout="hide" i]',
    '[data-block="donotprint" i]',
    '[class*="clickable-icon" i]',
    'li span[class*="ltx_tag" i][class*="ltx_tag_item" i]',
    'a[href^="#"][class*="anchor" i]:not([class*="heading-anchor" i])',
    'a[href^="#"][class*="ref" i]:not(.ltx_ref)',
    '[data-container*="most-viewed" i]',
    ".sidebar",
    ".Sidebar",
    "#sidebar",
    "#Sidebar",
    "#sitesub",
    '[data-link-name*="skip" i]',
    '[aria-label*="skip" i]',
    '[aria-label*="Skip" i]',
    "#skip-link",
    ".skip-link",
    ".skip-to-content",
    "#skip-to-content",
    '[href="#content"]',
    '[href="#main-content"]',
    '[href="#main"]',
    '[href^="#skip"]',
    'a[href^="#"][class*="skip"]',
    'a[aria-label*="skip to"]',
    'a[title*="skip to"]',
    ".copyright",
    "#copyright",
    "#rss",
    "#feed",
    ".gutter",
    "#primaryaudio",
    "#NYT_ABOVE_MAIN_CONTENT_REGION",
    '[data-testid="photoviewer-children-figure"] > span',
    "table.infobox",
    '.pencraft:not(.pc-display-contents)',
    '[data-optimizely="related-articles-section" i]',
    '[data-orientation="vertical"]',
    ".gh-header-sticky",
    '[data-testid="issue-metadata-sticky"]',
    '[role="listbox"]',
    '[role="option"]',
]

TEST_ATTRIBUTES = [
    "class", "id", "data-test", "data-testid", "data-test-id", "data-qa", "data-cy",
]

PARTIAL_SELECTORS = [
    "a-statement", "access-wall", "activitypub", "actioncall", "addcomment", "advert",
    "adlayout", "ad-tldr", "ad-placement", "ads-container", "_ad_", "after_content",
    "after_main_article", "afterpost", "allterms", "-alert-", "alert-box",
    "_archive", "around-the-web", "aroundpages", "article-author", "article-badges",
    "article-banner", "article-bottom-section", "article-bottom", "article-category",
    "article-card", "article-citation", "article__copy", "article_date", "article-date",
    "article-end ", "article_header", "article-header", "article__header", "article__hero",
    "article__info", "article-info", "article-meta", "article_meta", "article__meta",
    "articlename", "article-subject", "article_subject", "article-snippet",
    "article-separator", "article--share", "article--topics", "articletags",
    "article-tags", "article_tags", "articletitle", "article-title", "article_title",
    "articletopics", "article-topics", "article--lede", "articlewell", "associated-people",
    "audio-card", "author-bio", "author-box", "author-info", "author_info", "authorm",
    "author-mini-bio", "author-name", "author-publish-info", "authored-by", "avatar",
    "back-to-top", "backlink_container", "backlinks-section", "bio-block", "biobox",
    "blog-pager", "bookmark-", "-bookmark", "bottominfo", "bottomnav", "bottom-of-article",
    "bottom-wrapper", "brand-bar", "breadcrumb", "bcrumb", "brdcrumb", "button-wrapper",
    "buttons-container", "btn-", "-btn", "byline", "captcha", "card-text", "card-media",
    "card-post", "carouselcontainer", "carousel-container", "cat_header", "catlinks",
    "_categories", "card-author", "card-content", "chapter-list", "collections", "comments",
    "commentbox", "comment-button", "commentcomp", "comment-content", "comment-count",
    "comment-form", "comment-number", "comment-respond", "comment-thread", "comment-wrap",
    "complementary", "consent", "contact-", "content-card", "content-topics", "contentpromo",
    "context-bar", "context-widget", "copycontent", "core-collateral", "cover-", "created-date",
    "creative-commons_", "c-subscribe", "_cta", "-cta", "cta-", "cta_", "current-issue",
    "custom-list-number", "dateline", "dateheader", "date-header", "date-pub", "disclaimer",
    "disclosure", "discussion", "discuss_", "disqus", "donate", "donation", "dropdown",
    "eletters", "emailsignup", "engagement-widget", "enhancement-", "entry-author-info",
    "entry-categories", "entry-date", "entry-title", "entry-utility", "-error", "error-",
    "eyebrow", "expand-reduce", "external-anchor", "externallinkembedwrapper",
    "extra_services", "extra-title", "facebook", "fancy-box", "favorite", "featured-content",
    "feature_feed", "feedback", "feed-links", "field-site-sections", "fixheader",
    "floating-vid", "follower", "footer", "footnote-back", "footnoteback", "form-group",
    "for-you", "frontmatter", "further-reading", "fullbleedheader", "gated-", "gh-feed",
    "gist-meta", "goog-", "graph-view", "hamburger", "header_logo", "header-logo",
    "header-pattern", "hero-list", "hide-for-print", "hide-print", "hide-when-no-script",
    "hidden-print", "hidden-sidenote", "hidden-accessibility", "infoline",
    "instacartIntegration", "interlude", "interaction", "itemendrow", "invisible",
    "jumplink", "jump-to-", "keepreading", "keep-reading", "keep_reading", "keyword_wrap",
    "kicker", "labstab", "-labels", "language-name", "lastupdated", "latest-content",
    "-ledes-", "-license", "license-", "lightbox-popup", "like-button", "link-box",
    "links-grid", "links-title", "listing-dynamic-terms", "list-tags", "listinks",
    "loading", "loa-info", "logo_container", "ltx_role_refnum", "ltx_tag_bibitem",
    "ltx_error", "masthead", "marketing", "media-inquiry", "-menu", "menu-", "metadata",
    "might-like", "minibio", "more-about", "_modal", "-modal", "more-", "morenews",
    "morestories", "more_wrapper", "most-read", "move-helper", "mw-editsection",
    "mw-cite-backlink", "mw-indicators", "mw-jump-link", "nav-", "nav_",
    "navigation-post", "next-", "newsgallery", "news-story-title", "newsletter_",
    "newsletterbanner", "newslettercontainer", "newsletter-form", "newsletter-signup",
    "newslettersignup", "newsletterwidget", "newsletterwrapper", "not-found",
    "notessection", "nomobile", "noprint", "open-slideshow", "originally-published",
    "other-blogs", "outline-view", "pagehead", "page-header", "page-title",
    "paywall_message", "-partners", "permission-", "plea", "popular", "popup_links",
    "pop_stories", "pop-up", "post-author", "post-bottom", "post__category", "postcomment",
    "postdate", "post-date", "post_date", "post-details", "post-feeds", "postinfo",
    "post-info", "post_info", "post-inline-date", "post-links", "postlist", "post_list",
    "post_meta", "post-meta", "post__author", "postmeta", "post_more", "postnavi", "post-navigation",
    "postpath", "post-preview", "postsnippet", "post_snippet", "post-snippet",
    "post-subject", "posttax", "post-tax", "post_tax", "posttag", "post_tag", "post-tag",
    "post_time", "posttitle", "post-title", "post_title", "post__title", "post-ufi-button",
    "prev-post", "prevnext", "prev_next", "prev-next", "previousnext", "press-inquiries",
    "print-none", "print-header", "print:hidden", "privacy-notice", "privacy-settings",
    "profile", "promo_article", "promo-bar", "promo-box", "pubdate", "pub_date", "pub-date",
    "publish_date", "publish-date", "publication-date", "publicationName", "qr-code",
    "qr_code", "quick_up", "_rail", "ratingssection", "read_also", "readmore", "read-next",
    "read_next", "read_time", "read-time", "reading_time", "reading-time", "reading-list",
    "recent-", "recent-articles", "recentpost", "recent_post", "recent-post", "recommend",
    "redirectedfrom", "recirc", "register", "related", "relevant", "reversefootnote",
    "_rss", "rss-link", "screen-reader-text", "scroll_to", "scroll-to", "_search", "-search",
    "section-nav", "series-banner", "share-box", "sharedaddy", "share-icons", "sharelinks",
    "share-post", "share-print", "share-section", "show-for-print", "sidebartitle",
    "sidebar-content", "sidebar-wrapper", "sideitems", "sidebar-author", "sidebar-item",
    "side-box", "side-logo", "sign-in-gate", "similar-", "similar_", "similars-",
    "site-index", "site-header", "siteheader", "site-logo", "site-name", "site-wordpress",
    "skip-content", "skip-to-content", "skip-to-main", "skip-main", "skip-nav",
    "skip-navigation", "c-skip-link", "_skip-link", "-skip-link", "skip-link-", "-slider",
    "slug-wrap", "social-author", "social-shar", "social-date", "speechify-ignore",
    "speedbump", "sponsor", "springercitation", "sr-only", "_stats", "story-date",
    "story-navigation", "storyreadtime", "storysmall", "storypublishdate", "subject-label",
    "subhead", "submenu", "-subscribe-", "subscriber-drive", "subscription-", "_tags",
    "tags__item", "tag_list", "taxonomy", "table-of-contents", "tabs-", "terminaltout",
    "chakra-badge",
    "time-rubric", "timestamp", "time-read", "time-to-read", "tip_off", "tiptout", "-tout-",
    "toc-container", "toggle-caption", "tooltip", "topbar", "topic-list", "topic-subnav",
    "top-wrapper", "tree-item", "trending", "trust-feat", "trust-badge", "trust-project",
    "twitter", "u-hide", "upsell", "viewbottom", "visually-hidden", "welcomebox",
    "widget_pages",
]

FOOTNOTE_INLINE_REFERENCES = [
    "sup.reference", "cite.ltx_cite", 'sup[id^="fnr"]', 'span[id^="fnr"]',
    'span[class*="footnote_ref"]', "span.footnote-link", "a.citation",
    'a[id^="ref-link"]', 'a[href^="#fn"]', 'a[href^="#cite"]',
    'a[href^="#reference"]', 'a[href^="#footnote"]', 'a[href^="#r"]',
    'a[href^="#b"]', 'a[href*="cite_note"]', 'a[href*="cite_ref"]',
    "a.footnote-anchor", "span.footnote-hovercard-target a",
    'a[role="doc-biblioref"]', 'a[id^="fnref"]', 'a[id^="ref-link"]',
]

FOOTNOTE_LIST_SELECTORS = [
    "div.footnote ol", "div.footnotes ol", 'div[role="doc-endnotes"]',
    'div[role="doc-footnotes"]', "ol.footnotes-list", "ol.footnotes",
    "ol.references", 'ol[class*="article-references"]', "section.footnotes ol",
    'section[role="doc-endnotes"]', 'section[role="doc-footnotes"]',
    'section[role="doc-bibliography"]', "ul.footnotes-list", "ul.ltx_biblist",
    'div.footnote[data-component-name="FootnoteToDOM"]',
]

FOOTNOTE_BACK_REFERENCES = [
    'a[href^="#"][class*="anchor"]:not([class*="heading-anchor" i])',
    'a[href^="#"][class*="ref"]:not(.ltx_ref)',
    'a[class*="footnote-backref"]',
    ".footnote-backref",
]

ALLOWED_EMPTY_ELEMENTS = frozenset({
    "area", "audio", "base", "br", "circle", "col", "defs", "ellipse", "embed",
    "figure", "g", "hr", "iframe", "img", "input", "line", "link", "mask", "math",
    "meta", "object", "param", "path", "pattern", "picture", "polygon", "polyline",
    "rect", "source", "stop", "svg", "td", "th", "track", "use", "video", "wbr",
})

ALLOWED_ATTRIBUTES = frozenset({
    "data-callout", "data-callout-title",
    "alt", "allow", "allowfullscreen", "aria-label", "checked", "colspan", "controls",
    "data-latex", "data-src", "data-srcset", "data-lang", "dir", "display", "frameborder",
    "headers", "height", "href", "lang", "role", "rowspan", "src", "srcset", "title",
    "type", "width",
    "accent", "accentunder", "align", "columnalign", "columnlines", "columnspacing",
    "columnspan", "data-mjx-texclass", "depth", "displaystyle", "fence", "frame",
    "framespacing", "linethickness", "lspace", "mathsize", "mathvariant", "maxsize",
    "minsize", "movablelimits", "notation", "rowalign", "rowlines", "rowspacing",
    "rspace", "scriptlevel", "separator", "stretchy", "symmetric", "voffset", "xmlns",
})

ALLOWED_ATTRIBUTES_DEBUG = frozenset({"class", "id"})
